name: Dashboard Sync

on:
  repository_dispatch:
    types: [dashboard-sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          curl -L -X PATCH \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "description": "lezheng dashboard sync",
              "public": false,
              "files": {
                "dashboard-sync.json": {
                  "content": "${{ github.event.inputs.gist_content }}"
                }
              }
            }' \
            "https://api.github.com/gists/0e94dc8d34030821b67b5421d86b9537"
